FROM golang:1.22.0-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /server ./cmd/server/main.go

FROM alpine
RUN mkdir /configs

COPY --from=build /server /server
COPY ./configs/config.yaml /configs/config.yaml

EXPOSE 8080
CMD ["/server"]
