version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: deployments/Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/configs
    environment:
      STORE_ADDR: redis:6379

  client:
    build:
      context: .
      dockerfile: deployments/Dockerfile.client
    depends_on:
      - server
    volumes:
      - ./configs:/configs
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: